### ISSUE TITLE
Porting Library to Go

### ISSUE THREAD

**Issue by hanspr** [ChimeHQ/SwiftLSPClient#22]
Hi Matt,

My name is Hans Peyrot, sorry for the long explanation and using this channel to communicate. I'm close to finish a terminal text editor written in go based on the source of this project: https://github.com/zyedidia/micro

Right now, it is in a private repository, because I want to publish it when I feel that it is complete and very stable. And I'm very close to that. I will release it as open source project as the original one but, as a spin-off version, after contacting the original author too.

But one of the things that I'm missing, and would love to have, is an integration with Server Language Protocol. I'm worn out of fixing and improving the original project for the last several months. And I have to admit that I'm very new to go, actually all my coding experience in go comes from working on this project only.

I'm reaching out to you to see if you have some spare time to port your library to go, and work together integrating it to my version of this editor. I don't wish for much, with autocomplete I would be more than happy. Or If you could help me with a simple dirty framework to work with, that would be great too.

I googled, and I see that your are working on your own golang editor for the Mac. I personally code 90% of my time on headless Linux servers (mostly scripts), that is why I'm interested in having a really good terminal editor to work with. I also understand that you are a Mac developer, so you may find no interest at all on this port or this kind of project. I also assume than an SSH terminal editor should not create conflicts of interests with your current project.

I drop a small animated gif to show you how does the project looks like. Hope I could get your interest.

![features](https://user-images.githubusercontent.com/1572396/65269720-5fb88080-dadf-11e9-9a35-0179939ab2d9.gif)

Thanks in advance for your response, greeting. Hans

**Comment by mattmassicotte** [comment]
Hi Hans - great to hear about your project!

I wasn't aware of Micro, but it looks cool. And I'm sure your version will add some great stuff. I've been really excited to see just how much activity has been going on with editors!

A Go LSP client is a very interesting idea. I'm not certain a direct port of this library makes sense, but something that is more idiomatic Go would be great.

I'm afraid I've already gotten myself involved in some other side projects, and this just isn't one that I have time to work on directly. But, I would be happy to answer any questions you have. You can definitely do this!

Here are two libraries that might help you, if you get interested in looking into this:

https://github.com/sourcegraph/go-lsp
https://github.com/sourcegraph/jsonrpc2

And, of course, be sure to check out gopls, the official Go language server. I'm sure that source will be useful too.

**Comment by hanspr** [comment]
Thanks for your prompt answer, I was not aware of go-lsp, it looks as a start point. Thanks good luck.

**Comment by mattmassicotte** [comment]
Of course! Sorry I wasn't able to help more :(

**Comment by hanspr** [comment]
Hi Matt

Just to comment that I released my editor, I'll leave the LSP protocol for the end of the year, if you like to check the editor and tell your friends about it , would be nice to have some feedback from someone that has developed his own editor, thanks

https://github.com/hanspr/mi-ide

**Comment by mattmassicotte** [comment]
Congratulations on the release, and good luck!
