### ISSUE TITLE
Safe concurrent use

### ISSUE THREAD

**Issue by mattmassicotte** [ChimeHQ/SwiftLSPClient#25]
Sounds like there could be some issues with `ProtocolTransport` and synchronization.

None of the classes in this library are specifically intended to be used concurrently on different threads. In particular, `ProtocolTransport`, `LanguageServer`, and `LanguageServerProcessHost` have no synchronization built-in. These classes do provide the guarantee that overlapping request/responses to the language server are properly handled.

However, they must be locked and/or accessed on a serial queue. They are inherently not thread safe.

Could that be the root of the issue, @johnno1962?

**Comment by johnno1962** [comment]
I’ve reviewed and wrapped all calls in a synchroniser and there doesn’t seem to be a problem anymore. Sorry for the flash alarm here.
```
let lock = NSLock()
lock.lock()

func syncCall<RESP>(_ block: @escaping (@escaping (RESP) -> Void) -> Void) -> RESP {
    var theResponse: RESP?
    block({
        (response: RESP) in
        theResponse = response
        lock.unlock()
    })
    lock.lock()
    return theResponse!
}
```

**Comment by mattmassicotte** [comment]
No worries! I never experienced this because all of the accesses my app does are through a higher-level abstraction that synchronizes everything through a serial queue.

Do you think changes are still needed, or are things ok as-is?

**Comment by johnno1962** [comment]
Seems to be working fine as it is now all my locks are in a line.

**Comment by mattmassicotte** [comment]
ok great!

**Comment by mattmassicotte** [comment]
Sounds like perhaps there are still some concurrency issues. @johnno1962 if you'd like to post some crash reports and/or debugger output, I'd be happy to have a look.

**Comment by johnno1962** [comment]
Thanks for your help on this. I've managed to mash together an port of the project I was working on to lap that is giving me problems here: https://github.com/johnno1962/siteify/tree/port-to-lsp. Running this project would lie the best way to replicate the problems I'm seeing. The easiest way to set is up is the following:
```
$ git clone https://github.com/johnno1962/siteify -b port-to-lsp
$ cd siteify
$ swift build
$ open siteify.xcodeproj
# build Xcode project
$ .build/debug/siteify
$ open html/index.html
```
This generates a hyperlinked site for the project source. As committed it will generally run but if you comment out `!path.starts(with: ".build")` in citify/Siteify.swift, line 135 it will indeed your sources as well and this will generally hang with a message such as `not matching responder for numericId(6145), dropping message` but can run through to completion.

Obviously the code is a little ropey but what I'm looking for is to be able to code with LSP synchronously as I would in a script. Can you direct me to a better way?

**Comment by mattmassicotte** [comment]
I believe I understand the issue. The reason you are seeing this problem is that the underlying communication mechanism in place in SwiftLSPClient cannot be used synchronously. You're always in a race with the server. Locks cannot help if there aren't other threads involved.

The `StdioDataTransport` class, which uses `FileHandle` objects, depends on a current runtime (which you have) and that runloop actually having a chance to loop. Because your code is synchronous, it doesn't loop, so messages are pooling up waiting to be processed.

This is going to be tricky thing to fix, unfortunately. One way could be to make a wrapper for StdioDataTransport that uses the NSRunLoop API to allow the runloop to turn a few times before trying. You should also make a new `DataTransport` that does sync writes and then sync reads from stdio. In both cases, I'm not sure how to guarantee that you've given it enough time to be sure you've read everything. I don't have a lot of experience with synchronous I/O.

**Comment by mattmassicotte** [comment]
Oh, and almost forgot - this project of yours looks really cool! It's exactly the kind of thing I was hoping this library would be used for. Hopefully we can find a reasonable way to support the programming model you are after.

**Comment by johnno1962** [comment]
Thanks, it’s something I’ve been waiting to update for a while now. I was waiting for LSP to settle. The project is working (very nearly almost entirely) fine now. It seemed to be the lock in  generateId that had the most effect though I couldn’t be sure.

**Comment by mattmassicotte** [comment]
Yeah, LSP has taken a loooong time to get reasonable. Still very problematic in a number of situations. Ranges are particularly tough for non-UTF8 strings. Translating to Swift string ranges/NSRange is a huge pain. I use emoji for testing - have found lots of problems.

**Comment by mattmassicotte** [comment]
Given that (I think) we have this understood, I believe we can safely close this issue. The requirements for order-of-operation and/or concurrent access need to happen in the callers of this class.

**Comment by mattmassicotte** [comment]
I've added details in https://github.com/ChimeHQ/SwiftLSPClient/pull/29.

This class doesn't have a concurrency issue because it isn't safe to use from multiple thread simultaneously by design. I've expanded on the inline docs to outline that. You only needed locks because you added a delay that **also** moved execution to a background thread.
