### ISSUE TITLE
textDocument/references does not match spec

### ISSUE THREAD

**Issue by mattmassicotte** [ChimeHQ/SwiftLSPClient#26]
It looks like `ReferenceParams` does not match the LSP spec.

It is missing the `context` param. Am I understanding that correctly? @johnno1962 does the Swift language server work with this current implementation? I'll try out some Go servers and see what happens.

**Comment by mattmassicotte** [comment]
Ah, I see, `includeDeclaration` is optional, so most likely the Swift server is just being good about handling the missing parameter.

**Comment by mattmassicotte** [comment]
I believe that https://github.com/ChimeHQ/SwiftLSPClient/pull/27 will fix this. But, please look closely, as once this is merged, you'll need to slightly update your code.

**Comment by mattmassicotte** [comment]
Resolved with #27

**Comment by johnno1962** [comment]
Have synced with master this end.
