### ISSUE TITLE
Synchronous API

### ISSUE THREAD

**Issue by mattmassicotte** [ChimeHQ/SwiftLSPClient#32]
Per https://github.com/ChimeHQ/SwiftLSPClient/pull/30, there's interest in having a purely synchronous API.

**Comment by johnno1962** [comment]
I've updated https://github.com/johnno1962/siteify to be asynchronous but in the finish you can't have more than one outstanding request open on a file at the time so it makes little difference.

**Comment by mattmassicotte** [comment]
Ah yeah - I guess you have to depend on the server being capable of doing that. Hopefully at least now you're ready for it, should that change.
