### ISSUE TITLE
Type of `CompletionItem.documentation` doesn't match LSP spec

### ISSUE THREAD

**Issue by alidn** [ChimeHQ/SwiftLSPClient#44]
The LPS spec has type `string | MarkupContent` for `CompletionItem.documentation`, but this package has type `AnyCodable?`. If this is not indented, I can send a pull request. 
Thanks

**Comment by mattmassicotte** [comment]
Hello!

This was not intended. Because of the huge number of types required to support the spec, I've cut corners in many areas. This is one. I would be happy to accept a PR that corrects this!

**Comment by alidn** [comment]
Thanks! I'll send a pull request
